# Generated by Django 2.2.17 on 2021-04-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountpage',
            name='winRate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
