# Generated by Django 2.2.17 on 2021-04-07 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chess', '0002_auto_20210406_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='captured_piece',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='move',
            name='game',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='chess.Game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='move',
            name='move_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='player_black',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_black', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_white',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_white', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='move',
            name='square_from',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='move',
            name='square_to',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='move',
            unique_together={('move_id', 'game')},
        ),
        migrations.RemoveField(
            model_name='move',
            name='moveId',
        ),
    ]
